pipeline:
  name: pipeline-cab
  identifier: pipelinecab
  projectIdentifier: deployment
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Jenkins_build
        identifier: Jenkins_build
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: JenkinsBuild
                  name: Build_push
                  identifier: Build_push
                  spec:
                    connectorRef: jenkins
                    jobName: booking-app
                    jobParameter: []
                    delegateSelectors:
                      - helm-delegate
                    unstableStatusAsSuccess: false
                    useConnectorUrlForJobExecution: true
                  timeout: 10m
                  failureStrategies: []
        tags: {}
    - stage:
        name: Deploy_K8s
        identifier: Deploy_K8s
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: micro_2
          environment:
            environmentRef: pre_prod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: test
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
