pipeline:
  identifier: Build_cab_bookos_1684996864439
  name: Build cab-bookos
  orgIdentifier: default
  projectIdentifier: Jenkinsharness
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: prajwal8120/cab-bookos
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        variables: []
        when:
          pipelineStatus: Success
    - stage:
        name: Jenkins
        identifier: Jenkins
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: JenkinsBuild
                  name: JenkinsBuild_1
                  identifier: JenkinsBuild_1
                  spec:
                    connectorRef: Jenkinsconnector
                    jobName: bookos
                    jobParameter: []
                    unstableStatusAsSuccess: false
                    useConnectorUrlForJobExecution: false
                  timeout: 10m
        tags: {}
        delegateSelectors:
          - helm-delegate
  timeout: 10m
  allowStageExecutions: true
  delegateSelectors:
    - helm-delegate
