apiVersion: apps/v1
kind: Deployment
metadata:
  name: cab-booking
  namespace: harness-cab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cab-booking
  template:
    metadata:
      labels:
        app: cab-booking
    spec:
      containers:
        - name: cab-booking
          image: insta7120/cab:v1.0
          ports:
            - containerPort: 8080
