apiVersion: v1
kind: Service
metadata:
  name: cab-booking
  namespace: harness-cab
spec:
  selector:
    app: cab-booking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30090
  type: NodePort
